// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TH1.Data;

#nullable disable

namespace TH1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChuDe", b =>
                {
                    b.Property<int>("MaCD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCD"));

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCD");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("DonDatHang", b =>
                {
                    b.Property<int>("SoDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoDH"));

                    b.Property<bool>("DaGiao")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoaiNhan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("HTGiaoHang")
                        .HasColumnType("bit");

                    b.Property<bool>("HTThanhToan")
                        .HasColumnType("bit");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDH")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TriGia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoDH");

                    b.HasIndex("MaKH");

                    b.ToTable("DonDatHangs");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiKH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoaiKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenKH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("NhaXuatBan", b =>
                {
                    b.Property<int>("MaNXB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNXB"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNXB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNXB");

                    b.ToTable("NhaXuatBans");
                });

            modelBuilder.Entity("QuangCao", b =>
                {
                    b.Property<int>("STT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STT"));

                    b.Property<string>("HinhMinhHoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Href")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("STT");

                    b.ToTable("QuangCaos");
                });

            modelBuilder.Entity("Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhMinhHoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaCD")
                        .HasColumnType("int");

                    b.Property<int?>("MaNXB")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanXem")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaCD");

                    b.HasIndex("MaNXB");

                    b.ToTable("Saches");
                });

            modelBuilder.Entity("TH1.Models.Admin", b =>
                {
                    b.Property<int>("MaAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAdmin"));

                    b.Property<string>("DiaChiAdmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoaiAdmin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmailAdmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GioiTinhAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenAdmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhauAdmin")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgaySinhAdmin")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuyenAdmin")
                        .HasColumnType("int");

                    b.Property<string>("TenDNAdmin")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TH1.Models.CTThamDo", b =>
                {
                    b.Property<int>("MaCH")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("NoiDungTraLoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<int>("SoLanBinhChon")
                        .HasColumnType("int");

                    b.HasKey("MaCH");

                    b.ToTable("CTThamDos");
                });

            modelBuilder.Entity("TacGia", b =>
                {
                    b.Property<int>("MaTG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTG"));

                    b.Property<string>("DiaChiTG")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoaiTG")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenTG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTG");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("ThamDo", b =>
                {
                    b.Property<int>("MaCH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCH"));

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungThamDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TongSoBinhChon")
                        .HasColumnType("int");

                    b.HasKey("MaCH");

                    b.ToTable("ThamDos");
                });

            modelBuilder.Entity("VietSach", b =>
                {
                    b.Property<int>("MaTG")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTG");

                    b.HasIndex("MaSach");

                    b.ToTable("VietSaches");
                });

            modelBuilder.Entity("DonDatHang", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Sach", b =>
                {
                    b.HasOne("ChuDe", "ChuDe")
                        .WithMany("Saches")
                        .HasForeignKey("MaCD");

                    b.HasOne("NhaXuatBan", "NhaXuatBan")
                        .WithMany("Saches")
                        .HasForeignKey("MaNXB");

                    b.Navigation("ChuDe");

                    b.Navigation("NhaXuatBan");
                });

            modelBuilder.Entity("TH1.Models.CTThamDo", b =>
                {
                    b.HasOne("ThamDo", "ThamDo")
                        .WithMany("CTThamDos")
                        .HasForeignKey("MaCH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThamDo");
                });

            modelBuilder.Entity("VietSach", b =>
                {
                    b.HasOne("Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TacGia", "TacGia")
                        .WithMany("VietSach")
                        .HasForeignKey("MaTG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("ChuDe", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("NhaXuatBan", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("TacGia", b =>
                {
                    b.Navigation("VietSach");
                });

            modelBuilder.Entity("ThamDo", b =>
                {
                    b.Navigation("CTThamDos");
                });
#pragma warning restore 612, 618
        }
    }
}
